name: app_storage
description: "A simple and secure local storage package with support for primitives, collections, and JSON serialization."
version: 1.0.0
homepage: https://github.com/mixin27/app_storage
issue_tracker: https://github.com/mixin27/app_storage/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
